name: Python linting

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pre-commit hook
        run: |
          # Upgrade pip to the latest version
          python -m pip install --upgrade pip
          # Install pre-commit package
          python -m pip install pre-commit==3.3.1
          # Install the git hook scripts
          pre-commit install
      - name: Linting
        run: |
          # Run against all the files
          pre-commit run --all-files
